#include <stdio.h>
#include <stdbool.h>
#include <stdlib.h>
#include <pthread.h>
#include <sys/stat.h>
#include <math.h>
#include <time.h>
#define M 1.0e6

// Side length of square is 2 units
// Center of square and circle is the coordinate (1,1)
// Equation of circle is (x-1)^2 + (y-1)^2 - 1 = 0

struct data {
    double x;
    double y;
    bool inside;
};

struct thread_args {
    int num_points; // Number of random points to be generated by thread
    int num_inside; // Number of points inside the circle, out of all numbers generated by thread
    int* total_points_inside; // Count of all points inside the circle over all threads
    struct data *arr; // Array to store the coordinates of point generated along with a boolean indicating whether or not the point is inside the circle
};

void *runner(void* args) {
    struct thread_args* ptr = (struct thread_args*)args;
    for (int i=0;i<ptr->num_points;i++) {
        double x = ((float)rand()/(float)(RAND_MAX)) * 2.0;
        double y = ((float)rand()/(float)(RAND_MAX)) * 2.0;
        (ptr->arr)[i].x = x;
        (ptr->arr)[i].y = y;
        if ((x-1)*(x-1)+(y-1)*(y-1)-1<0) {
            (ptr->arr)[i].inside = true;
            (ptr->num_inside)++;
        }
        else (ptr->arr)[i].inside = false;
    }
    *(ptr->total_points_inside) += ptr->num_inside;
    printf("%d\n",*(ptr->total_points_inside));
}

int main(int argc, char **argv)
{
    /*read inputs n and k from input.txt*/
    FILE *input = fopen(argv[1], "r");
    if (input == NULL)
    {
        printf("%s: File doesn't exist\n", argv[1]);
        return 0;
    }
    FILE *out_file = fopen("output.txt", "a+");
    int n, num_threads; // Number of points, number of threads
    if (fscanf(input, "%d %d", &n, &num_threads)!=EOF) {
        srand((unsigned int)time(NULL));

        double time_spent=0.0;
        clock_t begin=clock();

        int total_points_inside = 0;
        int *ptr = &total_points_inside;
        int div = n/num_threads;
        pthread_t threads[num_threads]; // Array of thread identifier of different threads
        pthread_attr_t attr;
        pthread_attr_init(&attr);

        struct thread_args arguments[num_threads]; // Array of arguments to be passed to threads
        for (int i = 0;i<num_threads ;i++) {
            if (i!=num_threads-1) {
                arguments[i].num_points = div;
                arguments[i].num_inside = 0;
                arguments[i].arr = (struct data*)malloc(sizeof(struct data)*div);
                arguments[i].total_points_inside = ptr;
                pthread_create(&threads[i],&attr,runner,&arguments[i]);
            }
            else {
                arguments[i].num_points = n-(num_threads-1)*div;
                arguments[i].num_inside = 0;
                arguments[i].arr = (struct data*)malloc(sizeof(struct data)*(n-(num_threads-1)*div));
                arguments[i].total_points_inside = ptr;
                pthread_create(&threads[i],&attr,runner,&arguments[i]);
            }
        }
        for (int i=0;i<num_threads;i++) 
            pthread_join(threads[i], NULL);
        printf("%d\n",total_points_inside);
        double value_of_pi = 4.0*((double)(total_points_inside))/((double)n);
        clock_t end=clock();
        time_spent+=(double)(end - begin)*(M) / CLOCKS_PER_SEC;
        fprintf(out_file,"Time: %lf \xC2\xB5s\n\n",time_spent);
        fprintf(out_file,"Value Computed: %lf\n\n",value_of_pi);
        fprintf(out_file, "Log:\n\n");
        for (int i=0;i<num_threads;i++) {
            int points_inside_circle = arguments[i].num_inside;
            int points_inside_square = arguments[i].num_points - arguments[i].num_inside;
            int total_points = arguments[i].num_points;
            fprintf(out_file, "Thread%d: %d, %d\n",i+1,points_inside_square,points_inside_circle);
            fprintf(out_file,"Points inside the square: ");
            for (int j = 0;j<total_points;j++) {
                if (arguments[i].arr[j].inside==false) {
                    fprintf(out_file,"(%lf, %lf), ",arguments[i].arr[j].x, arguments[i].arr[j].y);
                }
            }
            fprintf(out_file,"\n");
            fprintf(out_file,"Points inside the circle: ");
            for (int j = 0;j<total_points;j++) {
                if (arguments[i].arr[j].inside==true) {
                    fprintf(out_file,"(%lf, %lf), ",arguments[i].arr[j].x, arguments[i].arr[j].y);
                }
            }
            fprintf(out_file,"\n\n");
            fflush(out_file);
        }
        fclose(input);
        fclose(out_file);
        for (int i=0;i<num_threads;i++) free(arguments[i].arr);
    }
    else {
        printf("No input written in the file\n");
    }
    return 0;
}